In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
data = pd.read_csv("C:/Users/ASUS/Desktop/FBS/Data science/Dataset/seattleweather1948-2017_1738467795684.csv")
data.head()

         DATE  PRCP  TMAX  TMIN  RAIN
0  1948-01-01  0.47    51    42  True
1  1948-01-02  0.59    45    36  True
2  1948-01-03  0.42    45    35  True
3  1948-01-04  0.31    45    34  True
4  1948-01-05  0.17    45    32  True

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25551 entries, 0 to 25550
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DATE    25551 non-null  object
 1   PRCP    25548 non-null  float64
 2   TMAX    25551 non-null  int64
 3   TMIN    25551 non-null  int64
 4   RAIN    25548 non-null  object
dtypes: float64(1), int64(2), object(2)
memory usage: 998.2+ KB

In [15]:
data.dropna(inplace = True)

In [16]:
X = data[['PRCP','TMAX','TMIN']]
X.head()

   PRCP  TMAX  TMIN
0  0.47    51    42
1  0.59    45    36
2  0.42    45    35
3  0.31    45    34
4  0.17    45    32

In [19]:
data['RAIN'] = data['RAIN'].replace({True:1,False:0})

C:\Users\ASUS\AppData\Local\Temp\ipykernel_6940\3995751637.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['RAIN'] = data['RAIN'].replace({True:1,False:0})

In [20]:
y = data['RAIN']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: RAIN, dtype: int64

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25548 entries, 0 to 25550
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DATE    25548 non-null  object
 1   PRCP    25548 non-null  float64
 2   TMAX    25548 non-null  int64
 3   TMIN    25548 non-null  int64
 4   RAIN    25548 non-null  int64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.2+ MB

In [22]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 10)

In [29]:
from sklearn.linear_model import LogisticRegression

In [31]:
model = LogisticRegression()

In [32]:
model.fit(X_train,y_train)

LogisticRegression()

In [33]:
train_pred = model.predict(X_train)

In [34]:
from sklearn.metrics import accuracy_score

In [35]:
accuracy_score(y_train,train_pred)

0.9295430081221254

In [36]:
test_pred =  model.predict(X_test)

In [37]:
accuracy_score(y_test,test_pred)

0.924853228962818