In [1]:
import pandas as pd

In [2]:
emp = pd.DataFrame({'Name':['Akshay', 'Rohit', 'Virat', 'John', 'Michael'],
                   'Age':[32, 45, 28, 32, 27],
                   'Salary':[45000, 38000, 29000, 50000, 41000],
                   })
emp

      Name  Age  Salary  DID
0   Akshay   32   45000    1
1    Rohit   45   38000    2
2    Virat   28   29000    2
3     John   32   50000    3
4  Michael   27   41000    4

In [4]:
emp['Salary'].mean()

np.float64(40600.0)

In [5]:
emp['Salary'].median()

np.float64(41000.0)

In [6]:
emp['Salary'].mode()

0    29000
1    38000
2    41000
3    45000
4    50000
Name: Salary, dtype: int64

In [7]:
emp['Age'].mode()

0    32
Name: Age, dtype: int64

In [14]:
emp['Name'].mode()

0     Akshay
1       John
2    Michael
3      Rohit
4      Virat
Name: Name, dtype: str

In [8]:
emp['Age'].unique()

array([32, 45, 28, 27])

In [15]:
emp['Name'].unique()

<StringArray>
['Akshay', 'Rohit', 'Virat', 'John', 'Michael']
Length: 5, dtype: str

In [10]:
emp['Age'].value_counts()

Age
32    2
45    1
28    1
27    1
Name: count, dtype: int64

In [16]:
emp['Name'].value_counts()

Name
Akshay     1
Rohit      1
Virat      1
John       1
Michael    1
Name: count, dtype: int64

In [11]:
iris = pd.read_csv('Datasets/Iris.csv')
iris.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [12]:
iris['Species'].value_counts()

Species
Setosa        50
Versicolor    50
Virginica     50
Name: count, dtype: int64

In [13]:
iris['Species'].unique()

<StringArray>
['Setosa', 'Versicolor', 'Virginica']
Length: 3, dtype: str

#create dataset for students with random marks (30 student,6 subjects).calculate total marks and percentage for every student.

In [17]:
emp['DID'] = [1, 2, 2, 3, 4]
emp

      Name  Age  Salary  DID
0   Akshay   32   45000    1
1    Rohit   45   38000    2
2    Virat   28   29000    2
3     John   32   50000    3
4  Michael   27   41000    4

In [18]:
emp['DID'] = [3, 2, 2, 1, 4]
emp

      Name  Age  Salary  DID
0   Akshay   32   45000    3
1    Rohit   45   38000    2
2    Virat   28   29000    2
3     John   32   50000    1
4  Michael   27   41000    4

In [19]:
emp.insert(2,value = ['Pune','Mumbai','CSN','Nashik','Dharashiv'],column = 'Address')
emp

      Name  Age    Address  Salary  DID
0   Akshay   32       Pune   45000    3
1    Rohit   45     Mumbai   38000    2
2    Virat   28        CSN   29000    2
3     John   32     Nashik   50000    1
4  Michael   27  Dharashiv   41000    4

In [20]:
emp.loc[len(emp)] = ['Roshan',67,'pune',100000,1]
emp

      Name  Age    Address  Salary  DID
0   Akshay   32       Pune   45000    3
1    Rohit   45     Mumbai   38000    2
2    Virat   28        CSN   29000    2
3     John   32     Nashik   50000    1
4  Michael   27  Dharashiv   41000    4
5   Roshan   67       pune  100000    1

In [ ]:
#emp = emp.drop(10)
emp.drop(10,inplace= True)

In [25]:
emp

      Name  Age    Address  Salary  DID
0   Akshay   32       Pune   45000    3
1    Rohit   45     Mumbai   38000    2
2    Virat   28        CSN   29000    2
3     John   32     Nashik   50000    1
4  Michael   27  Dharashiv   41000    4
5   Roshan   67       pune  100000    1

In [26]:
emp.loc[emp['Name'] == 'John']

   Name  Age Address  Salary  DID
3  John   32  Nashik   50000    1

In [28]:
emp.loc[emp['Name'] == 'Rohit'] = 90000
emp

TypeError: Invalid value '90000' for dtype 'str'. Value should be a string or missing value, got 'int' instead.