##### convert student data into excel

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Datasets/student_10.csv')
data

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     str
 1   Student ID  7 non-null      float64
 2   Class       10 non-null     int64
 3   Study hrs   8 non-null      float64
 4   Percentage  7 non-null      float64
dtypes: float64(3), int64(1), str(1)
memory usage: 532.0 bytes

In [4]:
data.isnull()

    Date  Student ID  Class  Study hrs  Percentage
0  False       False  False      False       False
1  False       False  False      False       False
2  False        True  False      False       False
3  False        True  False      False        True
4  False       False  False      False        True
5  False        True  False      False        True
6  False       False  False      False       False
7  False       False  False       True       False
8  False       False  False       True       False
9  False       False  False      False       False

In [5]:
data.isnull().sum()

Date          0
Student ID    3
Class         0
Study hrs     2
Percentage    3
dtype: int64

In [6]:
data.dropna()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
6  09-07-2021      1007.0     12        4.0        80.0
9  12-07-2021      1010.0     12        6.0        85.0

In [7]:
data

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [8]:
data.dropna(axis = 1)

         Date  Class
0  01-07-2021     10
1  02-07-2021     10
2  03-07-2021     10
3  06-07-2021     11
4  07-07-2021     11
5  08-07-2021     11
6  09-07-2021     12
7  10-07-2021     12
8  11-07-2021     12
9  12-07-2021     12

In [9]:
data

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [11]:
data2 = data.drop(['Date','Student ID'],axis = 1)
data2

   Class  Study hrs  Percentage
0     10        2.0        50.0
1     10        6.0        80.0
2     10        3.0        60.0
3     11        0.0         NaN
4     11        4.0         NaN
5     11       10.0         NaN
6     12        4.0        80.0
7     12        NaN        90.0
8     12        NaN        60.0
9     12        6.0        85.0

In [18]:
std_hr = data2['Study hrs'].mean()
std_hr

np.float64(4.375)

In [16]:
data2.fillna(0)

   Class  Study hrs  Percentage
0     10        2.0        50.0
1     10        6.0        80.0
2     10        3.0        60.0
3     11        0.0         0.0
4     11        4.0         0.0
5     11       10.0         0.0
6     12        4.0        80.0
7     12        0.0        90.0
8     12        0.0        60.0
9     12        6.0        85.0

In [19]:
data2.fillna({'Study hrs':std_hr,'Percentage':data2['Percentage'].mean()})

   Class  Study hrs  Percentage
0     10      2.000   50.000000
1     10      6.000   80.000000
2     10      3.000   60.000000
3     11      0.000   72.142857
4     11      4.000   72.142857
5     11     10.000   72.142857
6     12      4.000   80.000000
7     12      4.375   90.000000
8     12      4.375   60.000000
9     12      6.000   85.000000

In [20]:
data2.fillna({'Study hrs':std_hr})

   Class  Study hrs  Percentage
0     10      2.000        50.0
1     10      6.000        80.0
2     10      3.000        60.0
3     11      0.000         NaN
4     11      4.000         NaN
5     11     10.000         NaN
6     12      4.000        80.0
7     12      4.375        90.0
8     12      4.375        60.0
9     12      6.000        85.0

#data2.fillna(method = 'bfill') #depricated

In [21]:
data2.bfill()

   Class  Study hrs  Percentage
0     10        2.0        50.0
1     10        6.0        80.0
2     10        3.0        60.0
3     11        0.0        80.0
4     11        4.0        80.0
5     11       10.0        80.0
6     12        4.0        80.0
7     12        6.0        90.0
8     12        6.0        60.0
9     12        6.0        85.0

In [22]:
data2.ffill()

   Class  Study hrs  Percentage
0     10        2.0        50.0
1     10        6.0        80.0
2     10        3.0        60.0
3     11        0.0        60.0
4     11        4.0        60.0
5     11       10.0        60.0
6     12        4.0        80.0
7     12        4.0        90.0
8     12        4.0        60.0
9     12        6.0        85.0

In [23]:
data3 = data2.ffill()

In [24]:
data3

   Class  Study hrs  Percentage
0     10        2.0        50.0
1     10        6.0        80.0
2     10        3.0        60.0
3     11        0.0        60.0
4     11        4.0        60.0
5     11       10.0        60.0
6     12        4.0        80.0
7     12        4.0        90.0
8     12        4.0        60.0
9     12        6.0        85.0

In [25]:
groups = data3.groupby('Class')
groups

In [26]:
list(groups)

[(10,
     Class  Study hrs  Percentage
  0     10        2.0        50.0
  1     10        6.0        80.0
  2     10        3.0        60.0),
 (11,
     Class  Study hrs  Percentage
  3     11        0.0        60.0
  4     11        4.0        60.0
  5     11       10.0        60.0),
 (12,
     Class  Study hrs  Percentage
  6     12        4.0        80.0
  7     12        4.0        90.0
  8     12        4.0        60.0
  9     12        6.0        85.0)]

In [27]:
di = dict(list(groups))
di

{10:    Class  Study hrs  Percentage
 0     10        2.0        50.0
 1     10        6.0        80.0
 2     10        3.0        60.0,
 11:    Class  Study hrs  Percentage
 3     11        0.0        60.0
 4     11        4.0        60.0
 5     11       10.0        60.0,
 12:    Class  Study hrs  Percentage
 6     12        4.0        80.0
 7     12        4.0        90.0
 8     12        4.0        60.0
 9     12        6.0        85.0}

In [28]:
gr_10 = groups.get_group(10)
gr_11 = groups.get_group(11)
gr_12 = groups.get_group(12)

In [29]:
gr_10['Study hrs'].mean()

np.float64(3.6666666666666665)

In [30]:
gr = dict(list(data3.groupby(['Class','Study hrs'])))

In [31]:
gr

{(10,
  2.0):    Class  Study hrs  Percentage
 0     10        2.0        50.0,
 (10,
  3.0):    Class  Study hrs  Percentage
 2     10        3.0        60.0,
 (10,
  6.0):    Class  Study hrs  Percentage
 1     10        6.0        80.0,
 (11,
  0.0):    Class  Study hrs  Percentage
 3     11        0.0        60.0,
 (11,
  4.0):    Class  Study hrs  Percentage
 4     11        4.0        60.0,
 (11,
  10.0):    Class  Study hrs  Percentage
 5     11       10.0        60.0,
 (12,
  4.0):    Class  Study hrs  Percentage
 6     12        4.0        80.0
 7     12        4.0        90.0
 8     12        4.0        60.0,
 (12,
  6.0):    Class  Study hrs  Percentage
 9     12        6.0        85.0}