In [1]:
import pandas as pd

In [2]:
iris = pd.read_csv('Datasets/Iris.csv')
iris.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [3]:
s1 = iris['Sepal_Length']

In [4]:
type(s1)

pandas.Series

In [5]:
s1[0]

np.float64(5.1)

In [6]:
s1[0:5]

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: Sepal_Length, dtype: float64

In [7]:
i2 = iris.set_index(iris['Sepal_Length'])
i2

              Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
Sepal_Length
5.1                    5.1          3.5           1.4          0.2     Setosa
4.9                    4.9          3.0           1.4          0.2     Setosa
4.7                    4.7          3.2           1.3          0.2     Setosa
4.6                    4.6          3.1           1.5          0.2     Setosa
5.0                    5.0          3.6           1.4          0.2     Setosa
...                    ...          ...           ...          ...        ...
6.7                    6.7          3.0           5.2          2.3  Virginica
6.3                    6.3          2.5           5.0          1.9  Virginica
6.5                    6.5          3.0           5.2          2.0  Virginica
6.2                    6.2          3.4           5.4          2.3  Virginica
5.9                    5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [8]:
iris

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [9]:
iris[0:2]

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa

In [10]:
iris.loc[:,'Sepal_Length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: Sepal_Length, Length: 150, dtype: float64

In [11]:
iris.iloc[:,0]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: Sepal_Length, Length: 150, dtype: float64

In [12]:
iris.iloc[:,0:4]

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [13]:
X = iris.iloc[:,0:-1]
X

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [15]:
y = iris.iloc[:,-1]
y

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: Species, Length: 150, dtype: str

In [16]:
iris.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [17]:
y = iris['Sepal_Width']
y

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: Sepal_Width, Length: 150, dtype: float64

In [18]:
X = iris.drop('Sepal_Width',axis = 1)
X

     Sepal_Length  Petal_Length  Petal_Width    Species
0             5.1           1.4          0.2     Setosa
1             4.9           1.4          0.2     Setosa
2             4.7           1.3          0.2     Setosa
3             4.6           1.5          0.2     Setosa
4             5.0           1.4          0.2     Setosa
..            ...           ...          ...        ...
145           6.7           5.2          2.3  Virginica
146           6.3           5.0          1.9  Virginica
147           6.5           5.2          2.0  Virginica
148           6.2           5.4          2.3  Virginica
149           5.9           5.1          1.8  Virginica

[150 rows x 4 columns]